version: '3.8'

services:
  server:
    build:
      context: ./server
    command: yarn start:dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file: ./server/.env
    environment:
      NODE_ENV: development
      TELEGRAM_TOKEN: dev_token
      DATABASE_URL: "postgresql://mindflow:secret@postgres:5432/mindflow"
      REDIS_URL: "redis://redis:6379"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: yarn dev --host 0.0.0.0
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:3000"
    depends_on:
      - server